## Lab 02 - Sử dụng Thư viện NumPy làm việc với ma trận
----


 # Ten: Dang Quoc Toan
 # MSSV: 20051051
 # STT: 51

## 6) TÍNH TOÁN GIÁ TRỊ CÁC PHẦN TỬ TRONG MẢNG SỬ DỤNG NUMPY
---
### 6.1) Các phép tính toán học

In [1]:
import numpy as np
x = np.arange(8)
print("x     =", x)
print('----------------------------------')
#Các phép toán đã giới thiệu trong buổi 01
print("x + 5  =", x + 5)
print("x - 5  =", x - 5)
print(" -x    =", -x)
print("x * 2  =", x * 2)
print("x / 2  =", x / 2)
print("x // 2 =", x // 2)
print("x % 2  =", x % 2)
print("x ^ 3  =", x**3)

x     = [0 1 2 3 4 5 6 7]
----------------------------------
x + 5  = [ 5  6  7  8  9 10 11 12]
x - 5  = [-5 -4 -3 -2 -1  0  1  2]
 -x    = [ 0 -1 -2 -3 -4 -5 -6 -7]
x * 2  = [ 0  2  4  6  8 10 12 14]
x / 2  = [0.  0.5 1.  1.5 2.  2.5 3.  3.5]
x // 2 = [0 0 1 1 2 2 3 3]
x % 2  = [0 1 0 1 0 1 0 1]
x ^ 3  = [  0   1   8  27  64 125 216 343]


In [2]:
print("x      =", x)
print('---------------------------------')
#Sử dụng các phương thức của NumPy
print("x + 5  =", np.add(x,5))
print("x - 5  =", np.subtract(x, 5))
print("-x     =", np.negative(x))
print("x * 2  =", np.multiply(x,2))
print("x / 2  =", np.divide(x,2))
print("x // 2 =", np.floor_divide(x, 2))
print("x % 2  =", np.mod(x,2))
print("x ^ 3  =", np.power(x,3))

x      = [0 1 2 3 4 5 6 7]
---------------------------------
x + 5  = [ 5  6  7  8  9 10 11 12]
x - 5  = [-5 -4 -3 -2 -1  0  1  2]
-x     = [ 0 -1 -2 -3 -4 -5 -6 -7]
x * 2  = [ 0  2  4  6  8 10 12 14]
x / 2  = [0.  0.5 1.  1.5 2.  2.5 3.  3.5]
x // 2 = [0 0 1 1 2 2 3 3]
x % 2  = [0 1 0 1 0 1 0 1]
x ^ 3  = [  0   1   8  27  64 125 216 343]


### 6.2) Abs|Trigonometric Functions in NumPy
---

In [3]:
x = np.array([-2, -1, 0, 1, 2])
print(x)
print('----------------------')
print(np.abs(x))
print(np.absolute(x))


[-2 -1  0  1  2]
----------------------
[2 1 0 1 2]
[2 1 0 1 2]


In [4]:
theta = np.linspace(0, np.pi, 3)
print("theta      = ", theta)
print('------------------------------------------')
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))


theta      =  [0.         1.57079633 3.14159265]
------------------------------------------
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [5]:
x = [-1, 0, 1]
print("x         = ", x)
print('----------------------------------')
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
----------------------------------
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


## 6.3) Logarithmic and Exponential Functions
---

In [6]:
x = np.array([1, 2, 3])

print("x     =", x)
print('---------------------------')
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1 2 3]
---------------------------
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [7]:
x = np.array([1, 2, 4, 100])

print("x        =", x)
print('---------------------------')
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [  1   2   4 100]
---------------------------
ln(x)    = [0.         0.69314718 1.38629436 4.60517019]
log2(x)  = [0.         1.         2.         6.64385619]
log10(x) = [0.         0.30103    0.60205999 2.        ]


## 6.4 Rounding Functions
---

In [8]:
import numpy as np  
arr = np.array([20.8999,67.89899,54.43409]) 

print(arr)
print('----------------------------------')
#1) Làm tròn tới 1 số sau dấu ,
print(np.around(arr,1))

#2)Làm tròn tới 2 số sau dấu ,
print(np.around(arr,2))

#3)Làm tròn xuống số nguyên gần nhất
print(np.floor(arr))

#4)Làm tròn lên số nguyên gần nhất
print(np.ceil(arr))

[20.8999  67.89899 54.43409]
----------------------------------
[20.9 67.9 54.4]
[20.9  67.9  54.43]
[20. 67. 54.]
[21. 68. 55.]


## 7) Sắp xếp các phần tử trong mảng
---
np.sort: Thực hiện sắp xếp các phần tử trong mảng theo thứ tự tăng dần (hàng, cột)

In [9]:
#7.1) Sắp xếp các phần tử trong một vector
a = np.random.randint(1,33,15)

print('Vector ban đầu:\n', a)
print('---------------------------------')
#Sắp xếp vector a tăng dần
a_sort = np.sort(a)

#Sắp xếp vector a giảm dần:
#1) Lật vector a_sort để sắp xếp giảm dần
b_sort = np.flip(a_sort)
#2) sử dụng -np.sort(-x)
b_sort = -np.sort(-a)
print('Vector sắp xếp tăng dần: \n',a_sort)

print('Vector sắp xếp giảm dần: \n',b_sort)

Vector ban đầu:
 [ 6 10  1  9 32 19  3 23  7 26  4 18 31 26  5]
---------------------------------
Vector sắp xếp tăng dần: 
 [ 1  3  4  5  6  7  9 10 18 19 23 26 26 31 32]
Vector sắp xếp giảm dần: 
 [32 31 26 26 23 19 18 10  9  7  6  5  4  3  1]


In [10]:
#Sắp xếp các phần tử trong một vector
a = np.random.randint(1,33,15)

print('Vector ban đầu:\n', a)
print('--------------------------')
b_sort = -np.sort(-a)
print(b_sort)

Vector ban đầu:
 [21 32 14 23 17 13  6 20 31 12  4 23  7 18 30]
--------------------------
[32 31 30 23 23 21 20 18 17 14 13 12  7  6  4]


In [11]:
#7.1) Sắp xếp các phần tử trong một Ma trận
A = np.random.randint(1,30,30).reshape(5,6)
print('Ma trận A:\n', A)

Ma trận A:
 [[ 9 21  8  7 17 26]
 [11  1  2  9 19 27]
 [14 17 13 23  6  2]
 [27  7  4  7 10 15]
 [16 20 29 19  2 23]]


In [12]:
#1) Sắp xếp theo cột axis=0
a_sort1 = np.sort(A,axis=0)
print('Ma trận 1:\n', a_sort1)

Ma trận 1:
 [[ 9  1  2  7  2  2]
 [11  7  4  7  6 15]
 [14 17  8  9 10 23]
 [16 20 13 19 17 26]
 [27 21 29 23 19 27]]


In [13]:
#Sắp xếp các phần tử của ma trận A
#2) Sắp xếp theo hàng axis=1 | Default
a_sort2 = np.sort(A,axis=1)
print('Ma trận 2:\n', a_sort2)

Ma trận 2:
 [[ 7  8  9 17 21 26]
 [ 1  2  9 11 19 27]
 [ 2  6 13 14 17 23]
 [ 4  7  7 10 15 27]
 [ 2 16 19 20 23 29]]


In [14]:
#3) Chuyển thành vector và sắp xếp các phần tử tăng dần theo hàng
v_sort = np.sort(A,axis=None)
print('Vector: \n', v_sort)

Vector: 
 [ 1  2  2  2  4  6  7  7  7  8  9  9 10 11 13 14 15 16 17 17 19 19 20 21
 23 23 26 27 27 29]


In [15]:
#Sắp xếp tất cả các phần tử theo thứ tự tăng dần theo hàng
a_sort3 = np.sort(A, axis=None).reshape(A.shape[0],A.shape[1])
print('Ma trận 3:\n', a_sort3)

Ma trận 3:
 [[ 1  2  2  2  4  6]
 [ 7  7  7  8  9  9]
 [10 11 13 14 15 16]
 [17 17 19 19 20 21]
 [23 23 26 27 27 29]]


In [16]:
#thuộc tính kind=‘quicksort’- Default, ‘mergesort’, ‘heapsort’, ‘stable’
a_sort1 = np.sort(A,axis=0, kind='mergesort')
print('Ma trận 1:\n', a_sort1)

Ma trận 1:
 [[ 9  1  2  7  2  2]
 [11  7  4  7  6 15]
 [14 17  8  9 10 23]
 [16 20 13 19 17 26]
 [27 21 29 23 19 27]]


## 8) Tìm kiếm các phần tử trong mảng
---
np.where: Thực hiện tìm kiếm các phần tử trong mảng

In [17]:
import numpy as np
x = np.array([17, 2, 11, 1, 9, 15, 1, 3, 8, 1, 12, 13, 5])
#1) Tìm kiếm các phần tử có giá trị ==1
t1 = np.where(x==1)
print(t1)
print('1. Số phần tử thỏa mãn điều kiện = 1: ', t1[0].size)
print('-----------------------------------------------')
#2)Tìm kiếm các phần tử có giá trị >10
t2 = np.where(x>10)
print(t2)
print('2. Số phần tử thỏa mãn điều kiện>10: ', t2[0].size)
print('-----------------------------------------------')
#Tìm kiếm các phần tử có giá trị [5,12)
t3 = np.where((x>=5) & (x<12))
print(t3)
print('3.Số phần tử thỏa mãn điều kiện [5,10): ', t3[0].size)


(array([3, 6, 9], dtype=int64),)
1. Số phần tử thỏa mãn điều kiện = 1:  3
-----------------------------------------------
(array([ 0,  2,  5, 10, 11], dtype=int64),)
2. Số phần tử thỏa mãn điều kiện>10:  5
-----------------------------------------------
(array([ 2,  4,  8, 12], dtype=int64),)
3.Số phần tử thỏa mãn điều kiện [5,10):  4


In [18]:
import numpy as np
#Tìm kiếm trên ma trận
arr = np.array([(1, 2, 3, 4, 5, 4, 4),
                (7, 3, 4, 8, 9, 6, 7)])
#Tìm kiếm phần tử > 4
x = np.where(arr >4)

print('Ma trận A: \n',arr)
print('----------------------------------------')
print(x)
print('Số phần tử thỏa mãn điều kiện > 4:',x[0].size)

Ma trận A: 
 [[1 2 3 4 5 4 4]
 [7 3 4 8 9 6 7]]
----------------------------------------
(array([0, 1, 1, 1, 1, 1], dtype=int64), array([4, 0, 3, 4, 5, 6], dtype=int64))
Số phần tử thỏa mãn điều kiện > 4: 6


In [19]:
#Tìm kiếm và trả về kết quả với điều kiện đúng, sai
#Nếu Đúng thay bằng T, sai thay thế bằng F
x = np.where(arr >4,'T','F')
print(x)

[['F' 'F' 'F' 'F' 'T' 'F' 'F']
 ['T' 'F' 'F' 'T' 'T' 'T' 'T']]


# THỰC HÀNH 1:
---

**Yêu cầu 1: Đọc dữ liệu từ file Data_BMI.txt vào 2 vector tương ứng**
1. v_height: chứa dữ liệu chiều cao
2. v_Weight: Chứa dữ liệu cân nặng


In [37]:
# {Học viên viết code ở đây}
path = 'D:\GT\Lap_Trinh_PTDL\Data_BMI.txt'
v_height = np.loadtxt(path,usecols=0, dtype = np.float)
w_height = np.loadtxt(path,usecols=1,dtype = np.float)



C:\Users\DANG QUOC TOAN\AppData\Local\Temp\ipykernel_29284\1941206155.py:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  v_height = np.loadtxt(path,usecols=0, dtype = np.float)
C:\Users\DANG QUOC TOAN\AppData\Local\Temp\ipykernel_29284\1941206155.py:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  w_height = np.loadtxt(path,usecols=1,dty

In [38]:
v_height,w_height

(array([174., 189., 185., 195., 149., 189., 147., 154., 174., 169., 195.,
        159., 192., 155., 191., 153., 157., 140., 144., 172., 157., 153.,
        169., 185., 172., 151., 190., 187., 163., 179., 153., 178., 195.,
        160., 157., 189., 197., 144., 171., 185., 175., 149., 157., 161.,
        182., 185., 188., 181., 161., 140., 168., 176., 163., 172., 196.,
        187., 172., 178., 164., 143., 191., 141., 193., 190., 175., 179.,
        172., 168., 164., 194., 153., 178., 141., 180., 185., 197., 165.,
        168., 176., 181., 164., 166., 190., 186., 168., 198., 175., 145.,
        159., 185., 178., 183., 194., 177., 197., 170., 142., 160., 195.,
        190.]),
 array([ 96.,  87., 110., 104.,  61., 104.,  92., 111.,  90., 103.,  81.,
         80., 101.,  51.,  79., 107., 110., 129., 145., 139., 110., 149.,
         97., 139.,  67.,  64.,  95.,  62., 159., 152., 121.,  52.,  65.,
        131., 153., 132., 114.,  80., 152.,  81., 120., 108.,  56., 118.,
        126.,  76., 12

**Yêu cầu 2: Tạo vector v_height_m2 từ vector v_height theo yêu cầu sau:**
1. Chuyển đổi đơn vị của các phần tử từ cm sang m
2. Tính bình phương giá trị các phần tử


In [41]:
# {Học viên viết code ở đây}
v_height_m2 = []

for i in v_height:
    temp = 0
    temp = (i/100)**2
    v_height_m2.append(temp)
    



In [46]:
v_height_m2 = np.array(v_height_m2)
v_height_m2.reshape(1,100)

array([[3.0276, 3.5721, 3.4225, 3.8025, 2.2201, 3.5721, 2.1609, 2.3716,
        3.0276, 2.8561, 3.8025, 2.5281, 3.6864, 2.4025, 3.6481, 2.3409,
        2.4649, 1.96  , 2.0736, 2.9584, 2.4649, 2.3409, 2.8561, 3.4225,
        2.9584, 2.2801, 3.61  , 3.4969, 2.6569, 3.2041, 2.3409, 3.1684,
        3.8025, 2.56  , 2.4649, 3.5721, 3.8809, 2.0736, 2.9241, 3.4225,
        3.0625, 2.2201, 2.4649, 2.5921, 3.3124, 3.4225, 3.5344, 3.2761,
        2.5921, 1.96  , 2.8224, 3.0976, 2.6569, 2.9584, 3.8416, 3.4969,
        2.9584, 3.1684, 2.6896, 2.0449, 3.6481, 1.9881, 3.7249, 3.61  ,
        3.0625, 3.2041, 2.9584, 2.8224, 2.6896, 3.7636, 2.3409, 3.1684,
        1.9881, 3.24  , 3.4225, 3.8809, 2.7225, 2.8224, 3.0976, 3.2761,
        2.6896, 2.7556, 3.61  , 3.4596, 2.8224, 3.9204, 3.0625, 2.1025,
        2.5281, 3.4225, 3.1684, 3.3489, 3.7636, 3.1329, 3.8809, 2.89  ,
        2.0164, 2.56  , 3.8025, 3.61  ]])

**Yêu cầu 3: Tính chỉ số BMI của 100 người ngày theo công thức bên dưới, chỉ số BMI được làm tròn tới 1 số sau dấu “,”. Lưu kết quả vào vector v_bmi**


In [56]:
# {Học viên viết code ở đây}
v_bmi = []
count = 0
for i in v_height_m2:
    for j in w_height:
        temp = 0
        temp = round(j/i,1)
        v_bmi.append(temp)
        count += 1
    if count == 100:
        break
v_bmi = np.array(v_bmi)
v_bmi.reshape(1,100)



array([[31.7, 28.7, 36.3, 34.4, 20.1, 34.4, 30.4, 36.7, 29.7, 34. , 26.8,
        26.4, 33.4, 16.8, 26.1, 35.3, 36.3, 42.6, 47.9, 45.9, 36.3, 49.2,
        32. , 45.9, 22.1, 21.1, 31.4, 20.5, 52.5, 50.2, 40. , 17.2, 21.5,
        43.3, 50.5, 43.6, 37.7, 26.4, 50.2, 26.8, 39.6, 35.7, 18.5, 39. ,
        41.6, 25.1, 40.3, 36.7, 23.8, 50.2, 44.6, 17.8, 36.3, 34.7, 38.3,
        29.4, 30.4, 41.9, 23.1, 29.1, 17.8, 47.2, 17.8, 27.4, 44.6, 52.2,
        31.7, 19.5, 27.1, 44.9, 16.8, 38.6, 26.4, 24.8, 33. , 50.9, 34.4,
        29.7, 40.3, 16.8, 24.8, 46.2, 34.7, 39. , 40.6, 16.5, 46.6, 38.6,
        34.4, 46.2, 50.9, 31.7, 36.7, 20.1, 39.3, 51.5, 22.8, 45.9, 22.8,
        16.5]])

**Yêu cầu 4: Sắp xếp thứ tự các phần tử trong vector v_bmi theo chiều tăng dần, giảm dần**

In [61]:
# {Học viên viết code ở đây}
print("Sap Xep Giam Dan: ", -np.sort(-v_bmi))
print("Sap Xep Tang Dan: ", np.sort(v_bmi))


Sap Xep Giam Dan:  [52.5 52.2 51.5 50.9 50.9 50.5 50.2 50.2 50.2 49.2 47.9 47.2 46.6 46.2
 46.2 45.9 45.9 45.9 44.9 44.6 44.6 43.6 43.3 42.6 41.9 41.6 40.6 40.3
 40.3 40.  39.6 39.3 39.  39.  38.6 38.6 38.3 37.7 36.7 36.7 36.7 36.3
 36.3 36.3 36.3 35.7 35.3 34.7 34.7 34.4 34.4 34.4 34.4 34.  33.4 33.
 32.  31.7 31.7 31.7 31.4 30.4 30.4 29.7 29.7 29.4 29.1 28.7 27.4 27.1
 26.8 26.8 26.4 26.4 26.4 26.1 25.1 24.8 24.8 23.8 23.1 22.8 22.8 22.1
 21.5 21.1 20.5 20.1 20.1 19.5 18.5 17.8 17.8 17.8 17.2 16.8 16.8 16.8
 16.5 16.5]
Sap Xep Tang Dan:  [16.5 16.5 16.8 16.8 16.8 17.2 17.8 17.8 17.8 18.5 19.5 20.1 20.1 20.5
 21.1 21.5 22.1 22.8 22.8 23.1 23.8 24.8 24.8 25.1 26.1 26.4 26.4 26.4
 26.8 26.8 27.1 27.4 28.7 29.1 29.4 29.7 29.7 30.4 30.4 31.4 31.7 31.7
 31.7 32.  33.  33.4 34.  34.4 34.4 34.4 34.4 34.7 34.7 35.3 35.7 36.3
 36.3 36.3 36.3 36.7 36.7 36.7 37.7 38.3 38.6 38.6 39.  39.  39.3 39.6
 40.  40.3 40.3 40.6 41.6 41.9 42.6 43.3 43.6 44.6 44.6 44.9 45.9 45.9
 45.9 46.2 46.2 46.6 47.2 47

**Yêu cầu 5: Thống kê số lượng người theo từng mức dựa vào phân loại theo hình**

In [115]:
# {Học viên viết code ở đây}
UNDERWEIGHT = np.where(v_bmi<18.5)
Normal = np.where((v_bmi>18.5) & (v_bmi<24.9))
Overweight = np.where((v_bmi>25) & (v_bmi<29.9))
Obese = np.where((v_bmi)>30 & (v_bmi<34.9))
Extremely_Obese = np.where(v_bmi>35)
print("UNDERWEIGHT: ", UNDERWEIGHT[0].size)
print("NORMAL: ", Normal[0].size)
print("Overweight: ", Overweight[0].size)
print("Obese: ", Obese[0].size)
print("Extremely_Obese: ",Extremely_Obese[0].size)





UNDERWEIGHT:  9
NORMAL:  13
Overweight:  14
Obese:  100
Extremely_Obese:  47


## 9. MA TRẬN VUÔNG
---
### 9.1) det(a)

In [25]:
import numpy as np
a =np.array([( 1, 3, 1, 4),
             ( 3, 9, 5,15),
             ( 0, 2, 1, 1),
             ( 0, 4, 2, 3)])
print('Ma trận a:\n',a)
det_a =  np.linalg.det(a)
print('det(a) = ', det_a)

Ma trận a:
 [[ 1  3  1  4]
 [ 3  9  5 15]
 [ 0  2  1  1]
 [ 0  4  2  3]]
det(a) =  -3.999999999999999


In [26]:
import numpy as np
b =np.array([( 1, 2, 3, 4),
             (-2,-1, 4, 1),
             ( 3,-4,-5, 6),
             ( 1, 2, 3, 4)])
print('Ma trận b:\n',b)
det_b =  np.linalg.det(b)
print('det(b) = ', det_b)

Ma trận b:
 [[ 1  2  3  4]
 [-2 -1  4  1]
 [ 3 -4 -5  6]
 [ 1  2  3  4]]
det(b) =  0.0


In [27]:
a =np.array([( 3, 0, 2,-1),
             ( 1, 2, 0,-2),
             ( 4, 0, 6,-3),
             ( 5, 0, 2, 0)])
det_a =  np.linalg.det(a)
print(det_a)

20.000000000000007


### 9.2) ma trận nghịch đảo
---

In [28]:
import numpy as np
m = np.array([(1, 2, 3),
              (0, 1, 4),
              (5, 6, 0)])

#Xác định ma trận nghịc đảo của m
m1 = np.linalg.inv(m)
print(m1)

print(np.dot(m,m1).astype(int))

[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [73]:
#Trường hợp det(a) = 0; không tồn tại ma trận nghịch đảo.
import numpy as np
b =np.array([( 1, 2, 3, 4),
             (-2,-1, 4, 1),
             ( 3,-4,-5, 6),
             ( 1, 2, 3, 4)])
print('Ma trận b:\n',b)
det_b =  np.linalg.det(b)
print('det(b) = ', det_b)

b1 = np.linalg.inv(b)

Ma trận b:
 [[ 1  2  3  4]
 [-2 -1  4  1]
 [ 3 -4 -5  6]
 [ 1  2  3  4]]
det(b) =  0.0


LinAlgError: Singular matrix

In [ ]:
np.dot(a,b1)

In [ ]:
a1 = a.diagonal()
print(a1)

### 9.3) Đường chéo trong ma trận vuông
---
A) Lấy các phần tử trên đường chéo

In [ ]:
A = np.random.randint(1,100,(10,10))
print(A)

In [ ]:
#Lấy các phần tử trên đường chéo chính của 
#ma trận vuông A
d_A = A.diagonal()
print(d_A)

In [ ]:
#Lấy các phần tử nằm trên đường chéo chính
#của ma trận a 1 phần tử
d_A1 =  A.diagonal(2)
print(d_A1)

In [ ]:
#Lấy các phần tử nằm dưới đường chéo chính
#của ma trận a 4 phần tử
d_A1 =  A.diagonal(-1)
print(d_A1)

**B) Lấy ma trận tam giác**

In [ ]:
#MA TRẬN TAM GIÁC TRÊN
#ma trận A
d_A1 = np.triu(A)
print(d_A1)

In [ ]:
#MA TRẬN TAM GIÁC TRÊN
#Tạo ma trận là các phần tử trên đường chéo chính 
#của ma trận vuông A cách đường chéo chính
#về phía trên 2 đường
d_A1 = np.triu(A,2)
print(d_A1)

In [ ]:
#MA TRẬN TAM GIÁC TRÊN
#Tạo ma trận là các phần tử trên đường chéo chính 
#của ma trận vuông A cách đường chéo chính
#về phía dưới 3 đường
d_A1 = np.triu(A,-3)
print(d_A1)

In [ ]:
#MA TRẬN TAM GIÁC DƯỚI
#của ma trận vuông A
b_A1 = np.tril(A)
print(b_A1)

In [ ]:
b_A1 = np.tril(A,-1)
print(b_A1)

In [ ]:
b_A1 = np.tril(A,1)
print(b_A1)

**C) Trace of Matrix**

In [ ]:
#Tính trace của ma trận vuông A
trace_A = A.trace()
print('Trace of Matrix A: ',trace_A)

In [ ]:
#Cách 2: Tính trace của ma trận vuông A
trace_A = A.diagonal().sum()
print('Trace of Matrix A: ',trace_A)

#### D) Eigenvector | Eigenvalues
---

In [ ]:
#Tìm giá trị riêng, vector riêng của vector A
A = np.array([(3, 4,-2),
              (1, 4,-1),
              (2, 6,-1)])

eigenvalues, eigenvectors = np.linalg.eig(A)
print('Eigenvalues: ', eigenvalues)
print('Eigenvectors: \n',eigenvectors)

In [ ]:
t = eigenvectors[:,0]
print(t)

In [ ]:
print(A@t)

In [ ]:
print(3*t)

## THỰC HÀNH 2:
---
**Yêu cầu 1: Sử dụng vector_weigth trong bài thực hành 1 chuyển về ma trận kích thước 10 x 10**

In [82]:
# {Học viên viết code ở đây}
w_height.shape
weight = w_height.reshape(10,10)
weight





array([[ 96.,  87., 110., 104.,  61., 104.,  92., 111.,  90., 103.],
       [ 81.,  80., 101.,  51.,  79., 107., 110., 129., 145., 139.],
       [110., 149.,  97., 139.,  67.,  64.,  95.,  62., 159., 152.],
       [121.,  52.,  65., 131., 153., 132., 114.,  80., 152.,  81.],
       [120., 108.,  56., 118., 126.,  76., 122., 111.,  72., 152.],
       [135.,  54., 110., 105., 116.,  89.,  92., 127.,  70.,  88.],
       [ 54., 143.,  54.,  83., 135., 158.,  96.,  59.,  82., 136.],
       [ 51., 117.,  80.,  75., 100., 154., 104.,  90., 122.,  51.],
       [ 75., 140., 105., 118., 123.,  50., 141., 117., 104., 140.],
       [154.,  96., 111.,  61., 119., 156.,  69., 139.,  69.,  50.]])

**Yêu cầu 2: Cho biết ma trận weight có tồn tại ma trân nghịch đảo không? Nếu có hãy xác định ma trận weight-1 ?**

In [78]:
# {Học viên viết code ở đây}
np.linalg.det(weight)
np.linalg.inv(weight)


array([[ 0.20672933, -0.01828619, -0.08121229,  0.15165329, -0.05867193,
        -0.32128926,  0.00328234, -0.21117582,  0.1531515 ,  0.14765915],
       [-0.03378959, -0.00092993,  0.01637303, -0.02576189,  0.01204942,
         0.03860094, -0.00254169,  0.0334947 , -0.01916893, -0.01399406],
       [ 0.16001186, -0.01361912, -0.06334124,  0.11206935, -0.06692393,
        -0.2278292 ,  0.01233269, -0.16357827,  0.12566149,  0.10512262],
       [-0.20060155,  0.0096163 ,  0.08597968, -0.14951455,  0.06703284,
         0.32178178, -0.00847147,  0.21237844, -0.160284  , -0.14756298],
       [-0.1151341 ,  0.00896286,  0.04087891, -0.07066568,  0.02398925,
         0.16297821,  0.00236627,  0.09744888, -0.06997591, -0.06720453],
       [ 0.04172982, -0.00327195, -0.01645048,  0.02463278, -0.00963244,
        -0.05248791,  0.0053399 , -0.03159687,  0.01832677,  0.02128759],
       [ 0.46636016, -0.03988045, -0.19342132,  0.33291136, -0.13479078,
        -0.70496996,  0.01080126, -0.45280827

**Yêu cầu 3: Tạo vector_diagonal chứa các phần tử trên đường chéo chính của ma trận weight, tính trace của ma trận weight.**

In [83]:
# {Học viên viết code ở đây}
vector_diagonal = weight.diagonal()
print(vector_diagonal)
print("Trace = ", weight.trace())


[ 96.  80.  97. 131. 126.  89.  96.  90. 104.  50.]
Trace =  959.0


**Yêu cầu 4: Tìm giá trị lớn nhất của ma trận đường chéo trên và ma trận đường chéo dưới không bao gồm các phần tử trên đường chéo chính**

In [94]:
# {Học viên viết code ở đây}
max = 0
max_1 = 0
for i in range(1,10):
    temp = weight.diagonal(i)
    for j in temp:
        if j > max:
            max = j
print("Max Ma Tran Duong Cheo Tren = ", max)

for i in range(-10,1):
    temp = weight.diagonal(i)
    for j in temp:
        if j > max_1:
            max_1 = j
print("Max Ma Tran Duong Cheo Duoi =  ", max_1)



Max Ma Tran Duong Cheo Tren =  159.0
Max Ma Tran Duong Cheo Duoi =   158.0


In [93]:
weight

array([[ 96.,  87., 110., 104.,  61., 104.,  92., 111.,  90., 103.],
       [ 81.,  80., 101.,  51.,  79., 107., 110., 129., 145., 139.],
       [110., 149.,  97., 139.,  67.,  64.,  95.,  62., 159., 152.],
       [121.,  52.,  65., 131., 153., 132., 114.,  80., 152.,  81.],
       [120., 108.,  56., 118., 126.,  76., 122., 111.,  72., 152.],
       [135.,  54., 110., 105., 116.,  89.,  92., 127.,  70.,  88.],
       [ 54., 143.,  54.,  83., 135., 158.,  96.,  59.,  82., 136.],
       [ 51., 117.,  80.,  75., 100., 154., 104.,  90., 122.,  51.],
       [ 75., 140., 105., 118., 123.,  50., 141., 117., 104., 140.],
       [154.,  96., 111.,  61., 119., 156.,  69., 139.,  69.,  50.]])

## 10. Phép toán trên 2 mảng
---
### 10.1) Cộng/trừ

In [ ]:
import numpy as np

a = np.random.randint(1,20,(3,5))
b = np.random.randint(1,20,(3,5))
print('Matrix a: \n',a)
print('Matrix b: \n',b)

In [ ]:
a*b

In [ ]:
print('Matrix a: \n',a)
print('Matrix b: \n',b)

In [ ]:
#1) So sánh 2 ma trận
equal_ab = np.equal(a,b)
#hoặc equal_ab = a==b

print(equal_ab)

In [ ]:
#Phép cộng 2 ma trận
sum_ab = np.add(a,b)
#hoặc sum_ab = a + b
print (sum_ab)

In [ ]:
#Phép trừ 2 ma trận
sub_ab = np.subtract(a,b)
#hoặc sub_ab = a - b
print (sub_ab)

In [ ]:
c = np.random.randint(1,20,(5,4))
print('Matrix a: \n',a)
print('Matrix c: \n',c)

In [ ]:
#3) Tích của 2 ma trận:
#multi_ac = np.dot(a,c)
multi_ac1 = a@c
print(multi_ac)

In [ ]:
#Lưu ý: Nếu sử dụng phép toán *, 
#thực hiện nhân từng phần của ma trận a và b
#a, b có cùng kích thước.

multi_ac = a*b
print(multi_ac)

In [ ]:
#Tích của 2 vector:
vector_a = np.random.randint(1,20,10)
vector_b = np.random.randint(1,20,10)
#Thực hiện tính tích của 2 vector
#Kết quả trả về một số
vector_ab = vector_a @ vector_b

print('Vector a:\n',vector_a)
print('Vector b:\n',vector_b)
print('Tích của hai vector:\n',vector_ab)

# THỰC HÀNH 3
---
**Yêu cầu 1: Chuyển vector_height, vector_weigth trong bài thực hành 1 về ma trận height, weight kích thước 10 x 10.**

Thực hiện các phép toán: So sánh; Cộng; Trừ; Nhân hai ma trận height và weighT

In [103]:
# {Học viên viết code ở đây}
height  = v_height.reshape(10,10)
print("So Sanh 2 Ma Tran: ", np.equal(height,weight))
print("Cong 2 Ma Tran: ", np.add(height,weight))
print("Tru 2 Ma Tran: " , np.subtract(height, weight))
print("Nhan 2 Ma Tran: ",  height@weight)


So Sanh 2 Ma Tran:  [[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]]
Cong 2 Ma Tran:  [[270. 276. 295. 299. 210. 293. 239. 265. 264. 272.]
 [276. 239. 293. 206. 270. 260. 267. 269. 289. 311.]
 [267. 302. 266. 324. 239. 215. 285. 249. 322. 331.]
 [274. 230. 260. 291. 310. 321. 311. 224. 323. 266.]
 [295. 257. 213. 279. 308. 261. 310. 292. 233. 292.]
 [303. 230. 273. 277. 312. 276. 264. 305. 234. 231.]
 [245. 284. 24

## 11. Rank(A); A.T
---
### 11.1) Hạng của ma trận

In [ ]:
A=np.array([(-1, 2, 0, 4, 5,-3),
            ( 3,-7, 2, 0, 1, 4),
            ( 2,-5, 2, 4, 6, 1),
            ( 4,-9, 2,-4,-4, 7)])
#Tìm hạng của ma trận A
rank_a = np.linalg.matrix_rank(A)
print(A)
print('Rank(A) = ', rank_a)

In [ ]:
#Hạng của ma trận 0
A_0 = np.zeros((4,5))
print(A_0)
rank = np.linalg.matrix_rank(A_0)
print('Rank(A_0) = ', rank)

In [ ]:
#Hạng của ma trận có các phần tử bằng nhau
A_cons = np.full((4,5),5)
print(A_cons)
rank_c = np.linalg.matrix_rank(A_cons)
print('Rank(A_cons) = ', rank_c)

In [ ]:
#Hạng của ma trận có det(A)=0
import numpy as np
B =np.array([( 1, 2, 3, 4),
             (-2,-1, 4, 1),
             ( 3,-4,-5, 6),
             ( 1, 2, 3, 4)])
print('Ma trận B1:\n',B)
det_b =  np.linalg.det(B)
print('det(B1) = ', det_b)
rank_b = np.linalg.matrix_rank(B)
print('Rank(B1) = ', rank_b)

In [ ]:
#Hạng của ma trận có det(A)#0
import numpy as np
B =np.array([( 1, 3, 1, 4),
             ( 3, 9, 5,15),
             ( 0, 2, 1, 1),
             ( 0, 4, 2, 3)])
print('Ma trận B2:\n',B)
det_b =  np.linalg.det(B)
print('det(B2) = ', round(det_b,2))
rank_b = np.linalg.matrix_rank(B)
print('Rank(B2) = ', rank_b)

### 11.2) Ma trận chuyển vị
---

In [ ]:
#MA TRẬN CHUYỂN VỊ
A=np.array([(-1, 2, 0, 4, 5,-3),
            ( 3,-7, 2, 0, 1, 4),
            ( 2,-5, 2, 4, 6, 1),
            ( 4,-9, 2,-4,-4, 7)])
#Tìm ma trận chuyển vị của A
A_T = A.T
print('Ma trận A:\n',A)
print('Ma trận chuyển vị của A:\n',A_T)

In [ ]:
B =np.array([( 1, 3, 1, 4),
             ( 3, 9, 5,15),
             ( 0, 2, 1, 1),
             ( 0, 4, 2, 3)])
#Tìm ma trận chuyển vị của B
B_T = B.T
print('Ma trận B:\n',B)
print('Ma trận chuyển vị của B:\n',B_T)

## THỰC HÀNH 4
---
Yêu cầu 4.1: Học viên tìm ma trận nghịch đảo và hạng của ma trận Height, Weight trong bài thực hành số 3:

In [105]:
# {Học viên viết code ở đây}
print("Ma Tran Nghich Dao Height = ", height.T)
print("Ma Tran Nghich Dao Weight = ", weight.T)



Ma Tran Nghich Dao Height =  [[174. 195. 157. 153. 175. 168. 191. 153. 164. 178.]
 [189. 159. 153. 178. 149. 176. 141. 178. 166. 183.]
 [185. 192. 169. 195. 157. 163. 193. 141. 190. 194.]
 [195. 155. 185. 160. 161. 172. 190. 180. 186. 177.]
 [149. 191. 172. 157. 182. 196. 175. 185. 168. 197.]
 [189. 153. 151. 189. 185. 187. 179. 197. 198. 170.]
 [147. 157. 190. 197. 188. 172. 172. 165. 175. 142.]
 [154. 140. 187. 144. 181. 178. 168. 168. 145. 160.]
 [174. 144. 163. 171. 161. 164. 164. 176. 159. 195.]
 [169. 172. 179. 185. 140. 143. 194. 181. 185. 190.]]
Ma Tran Nghich Dao Weight =  [[ 96.  81. 110. 121. 120. 135.  54.  51.  75. 154.]
 [ 87.  80. 149.  52. 108.  54. 143. 117. 140.  96.]
 [110. 101.  97.  65.  56. 110.  54.  80. 105. 111.]
 [104.  51. 139. 131. 118. 105.  83.  75. 118.  61.]
 [ 61.  79.  67. 153. 126. 116. 135. 100. 123. 119.]
 [104. 107.  64. 132.  76.  89. 158. 154.  50. 156.]
 [ 92. 110.  95. 114. 122.  92.  96. 104. 141.  69.]
 [111. 129.  62.  80. 111. 127.  59.  90

In [107]:
#{Học viên kiểm tra và trả lời các câu hỏi vào đây?}
print("Rank Height = ", np.linalg.matrix_rank(height))
print("Rank Weight = ", np.linalg.matrix_rank(weight))

Rank Height =  10
Rank Weight =  10
